import { getLayout } from '@/components/layouts/layout';
import Order from '@/components/orders/order-view';
import Seo from '@/components/seo/seo';
import Spinner from '@/components/ui/loaders/spinner/spinner';
import { useOrder } from '@/framework/order';
import { useRouter } from 'next/router';
import { useSettings } from '@/framework/settings';

export { getServerSideProps } from '@/framework/order.ssr';

/**
 * Kolshi F.3.5 — single-order thank-you redirect.
 *
 * Kept as a thin alias over the order detail view so existing deep
 * links (receipts / email templates generated by the server) continue
 * to work. The multi-order flow uses `/orders/order-received?ids=…`.
 */
export default function OrderThankYouPage() {
  const { settings } = useSettings();
  const { query } = useRouter();
  const { order, isLoading, isFetching } = useOrder({
    tracking_number: query.tracking_number!.toString(),
  });

  if (isLoading) {
    return <Spinner showText={false} />;
  }

  return (
    <>
      <Seo noindex nofollow />
      <Order
        settings={settings}
        order={order}
        loadingStatus={!isLoading && isFetching}
      />
    </>
  );
}

OrderThankYouPage.getLayout = getLayout;
